### ISSUE TITLE
Stats: Insights page does not load

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#331]
In the latest version (2.8.0 release) the Stats Insights page does not load.

If you are on another Stats tab (e.g. Days) and try to open Insights, only the placeholders appear:

![screen shot 2017-08-19 at 12 53 45 pm](https://user-images.githubusercontent.com/8658164/29486459-e583817e-84dd-11e7-890e-a0b1e7037af9.png)

The console includes two errors:

```
build.js:304 Uncaught TypeError: t.utcOffset(...).format is not a function
2build.js:303 Uncaught TypeError: Cannot read property '__reactInternalInstance$bnbops4c7nk3c1kq2yrpo2bj4i' of null
```

If you switch to another site while on this Insights page, the page modules may appear but the content doesn't load:

![screen shot 2017-08-19 at 12 58 04 pm](https://user-images.githubusercontent.com/8658164/29486479-43610fa0-84de-11e7-8087-d0705dcd06fd.png)

In this case I see these console errors:

```
build.js:303 Uncaught TypeError: Cannot read property '_currentElement' of null_updateRenderedComponent
build.js:303 Uncaught TypeError: Cannot read property '__reactInternalInstance$bnbops4c7nk3c1kq2yrpo2bj4i' of null
```

At least once when I was on this Insights page (with the modules appearing but no content loading) I got stuck there — trying to switch to another part of the app changed the masterbar and page title (and sometimes the sidebar) but didn't fully navigate to the new part of the app:

![screen shot 2017-08-19 at 1 03 45 pm](https://user-images.githubusercontent.com/8658164/29486498-eae8ea40-84de-11e7-86a2-1af9890ac5b6.png)

##### Tested on Mac OS 10.12.6, WP Desktop 2.8.0 (stable release)

**Comment by SiobhyB** [comment]
This was also reported in 664582-z. The user's using the Windows app and noticed the issue after upgrading to 2.7.0:

![ffmgwoz](https://user-images.githubusercontent.com/2998162/30209465-24dfc4b0-9490-11e7-9627-d3a35acb4725.png)

**Comment by johngodley** [comment]
This looks like it might have been a Calypso problem. I've tried it in 3.1.0 and I can't reproduce the error. Does it still happen for you?

**Comment by rachelmcr** [comment]
This was specific to the desktop app, but I can no longer reproduce it in 3.2.0 so I'll close the issue.
